'use client';
import {useEffect,useMemo,useState} from 'react';
import {FileSpreadsheet,Upload,Eye,ChevronLeft,ChevronRight,Printer,Save,History,AlertTriangle,CheckCircle2} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {moneyBR,stores} from '@/lib/model';
import {erpFields,parseCsvText,parseErpDate,parseErpMoney,suggestErpMappings,normalizeErpStatus} from '@/lib/erp-csv';

const labels:any={payable:'Contas a pagar',receivable:'Contas a receber'};
const fmt=(d:string)=>d?d.split('-').reverse().join('/'):'—';
const periodName=(kind:string)=>kind==='week'?'Semana iniciada':'Mês';
function Metric({label,value,detail,tone}:{label:string;value:string;detail:string;tone?:string}){return <div className={'metric '+(tone||'')}><div className="metric-top"><span>{label}</span></div><strong>{value}</strong><small>{detail}</small></div>;}
function changeText(current:number,previous:number|undefined){if(previous===undefined)return'Sem importação do período anterior';const delta=current-previous;const pct=previous?` · ${(delta/previous*100).toFixed(1)}%`:' · base anterior zerada';return `${delta>0?'+':''}${moneyBR(delta)}${pct}`;}
function savePdf(){const article=document.querySelector('.erp-print');if(!article)return;const w=window.open('','_blank');if(!w)return;w.document.write('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Relatório gerencial União</title><style>body{font:12px Arial;color:#23334b;margin:24px}h1{font-size:22px}h2{margin-top:26px}table{border-collapse:collapse;width:100%;margin:12px 0}td,th{text-align:left;border-bottom:1px solid #ddd;padding:7px}small{color:#68778b}.cards{display:flex;gap:10px}.cards>div{border:1px solid #ddd;padding:12px;flex:1}button{display:none}@page{size:A4;margin:12mm}</style><body>'+article.innerHTML+'</body></html>');w.document.close();w.focus();w.print();}
export default function ErpReporting({view,from,to,store,records,canWrite,onImported}:{view:string;from:string;to:string;store:string;records:any[];canWrite:boolean;onImported:()=>void}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[table,setTable]=useState<any>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[kind,setKind]=useState(view==='receivable'?'receivable':'payable'),[importStore,setImportStore]=useState(store==='Todas as lojas'?'Loja 1':store),[importFrom,setImportFrom]=useState(from),[importTo,setImportTo]=useState(to),[busy,setBusy]=useState(false),[detailKind,setDetailKind]=useState(''),[detail,setDetail]=useState<any>(null),[page,setPage]=useState(1),[note,setNote]=useState(''),[saved,setSaved]=useState(false),[selectedClose,setSelectedClose]=useState<any>(null);
 async function reload(){setLoading(true);setError('');try{const q=new URLSearchParams({from,to,store,horizon:'30'});const r=await fetch('/api/erp?'+q,{cache:'no-store'});const x:any=await r.json();if(!r.ok)throw Error(x.error);setData(x);}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{reload();},[from,to,store]);
 useEffect(()=>{setImportFrom(from);setImportTo(to);if(store!=='Todas as lojas'&&store!=='Rede')setImportStore(store);},[from,to,store]);
 useEffect(()=>{if(data?.stores?.length&&!data.stores.includes(importStore))setImportStore(data.stores[0]);},[data?.stores,importStore]);
 useEffect(()=>{if(!detailKind)return;fetch(`/api/erp?details=1&kind=${detailKind}&from=${from}&to=${to}&store=${encodeURIComponent(store)}&page=${page}&size=50`).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setDetail(d);}).catch((e:any)=>setError(e.message));},[detailKind,page,from,to,store]);
 const parsed=useMemo(()=>{
  if(!table)return {rows:[],errors:[]};const errors:any[]=[],rows:any[]=[];const ix=(key:string)=>mapping[key]?table.headers.indexOf(mapping[key]):-1;const value=(row:string[],key:string)=>{const i=ix(key);return i<0?'':row[i]||'';};
  table.rows.forEach((raw:string[],i:number)=>{const dueDate=parseErpDate(value(raw,'dueDate')),amount=parseErpMoney(value(raw,'amount'));if(!dueDate||amount===null||amount<=0){errors.push({line:i+2,reason:!dueDate?'Vencimento inválido ou não mapeado':'Valor inválido ou não mapeado'});return;}const rawStatus=value(raw,'status'),paidDate=parseErpDate(value(raw,'paidDate'))||null,settledRaw=value(raw,'settled'),settledParsed=settledRaw?parseErpMoney(settledRaw):null,remRaw=value(raw,'remaining'),remainingParsed=remRaw?parseErpMoney(remRaw):null;const settled=settledParsed??(remainingParsed!==null?Math.max(0,amount-remainingParsed):paidDate||/pago|recebid|liquid|baixad|quitad/i.test(rawStatus)?amount:0);const remaining=remainingParsed??Math.max(0,amount-settled);if(settled<0||settled>amount||remaining<0||remaining>amount){errors.push({line:i+2,reason:'Valor pago ou saldo em aberto fora do valor do título'});return;}const name=value(raw,'name'),document=value(raw,'document')||value(raw,'externalId'),explicitId=value(raw,'externalId');const externalId=explicitId||`${document||'titulo'}|${name}|${dueDate}|${amount}|${i}`;rows.push({externalId,dueDate,paidDate,name,document,category:value(raw,'category')||'Não classificado',status:normalizeErpStatus(rawStatus,remaining),amount,settled,remaining,raw:{}});});
  const ids=new Set<string>(),dupes=rows.filter(r=>ids.has(r.externalId)||!ids.add(r.externalId));for(const d of dupes)errors.push({line:'—',reason:`Identificador repetido: ${d.externalId}`});return {rows,errors};
 },[table,mapping]);
 async function pickFile(f:File|null){setFile(f);setTable(null);setMapping({});if(!f)return;if(f.size>6000000){setError('O CSV precisa ter até 6 MB por importação.');return;}if(!/\.(csv|txt|tsv)$/i.test(f.name)){setError('Exporte o arquivo do ERP como CSV UTF-8 e selecione novamente.');return;}try{const t=parseCsvText(await f.text());if(t.rows.length>10000)throw Error('Limite de 10.000 títulos por arquivo. Divida a exportação por período ou loja.');setTable(t);setMapping(suggestErpMappings(t.headers));setError('');}catch(e:any){setError(e.message);}}
 async function importFile(){if(!file||!table||parsed.errors.length||!parsed.rows.length)return;setBusy(true);setError('');try{const r=await fetch('/api/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'import',kind,store:importStore,from:importFrom,to:importTo,filename:file.name,rows:parsed.rows})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setFile(null);setTable(null);setMapping({});await reload();onImported();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function closePeriod(){if(!data?.summary?.importedRows)return;setBusy(true);setError('');try{const closingStore=store==='Todas as lojas'?'Rede':store,id=crypto.randomUUID();const r=await fetch('/api/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'close',id,store:closingStore,from,to,title:`Fechamento gerencial · ${fmt(from)} a ${fmt(to)}`,note})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSaved(true);setNote('');await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const isReport=view==='report';const current=data?.summary;const financeKinds=isReport?['payable','receivable']:[view];const treasury=records.filter(r=>r.date>=from&&r.date<=to);const openIssues=treasury.filter(r=>r.kind==='issue'&&r.data.status!=='Resolvido').length;const routines=treasury.filter(r=>r.kind==='routine'&&r.data.status==='Concluído');const cashChecks=treasury.filter(r=>r.kind==='cash');
 return <div className="erp-reporting">
  {error&&<div className="alert"><AlertTriangle size={17}/>{error}</div>}
  {isReport?<>
   <section className="panel"><div className="panel-heading"><div><h2>Resumo para o supervisor</h2><p>Contas do ERP consolidadas com os indicadores operacionais do período.</p></div><button className="secondary" onClick={savePdf}><Printer size={16}/>Imprimir / salvar PDF</button></div>
    {!data&&!loading?<p>Carregando dados gerenciais…</p>:<article className="erp-print"><div className="report-brand"><img src="/logo_horizontal_oficial.png" alt="União Supermercados"/><span>Fechamento gerencial</span></div><h1>{fmt(from)} a {fmt(to)}</h1><p>{store==='Todas as lojas'?'Todas as lojas':store} · Importações mais recentes disponíveis: {data?.inRangeBatches?.length||0}</p>
     <div className="metrics"><Metric label="Pagamentos previstos" value={current?moneyBR(current.payable.expected):'—'} detail={`${current?.payable.expectedCount||0} títulos no período`} tone="red"/><Metric label="Pagamentos realizados" value={current?moneyBR(current.payable.realized):'—'} detail={`${current?.payable.realizedCount||0} títulos baixados`} /><Metric label="Recebimentos previstos" value={current?moneyBR(current.receivable.expected):'—'} detail={`${current?.receivable.expectedCount||0} títulos no período`} tone="green"/><Metric label="Recebimentos realizados" value={current?moneyBR(current.receivable.realized):'—'} detail={`${current?.receivable.realizedCount||0} títulos recebidos`}/></div>
     <h2>Em aberto e vencidos</h2><Table><TableHeader><TableRow><TableHead>Indicador</TableHead><TableHead>Contas a pagar</TableHead><TableHead>Contas a receber</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Saldo em aberto</TableCell><TableCell>{current?moneyBR(current.payable.open):'—'} <small>{current?.payable.openCount||0} títulos</small></TableCell><TableCell>{current?moneyBR(current.receivable.open):'—'} <small>{current?.receivable.openCount||0} títulos</small></TableCell></TableRow><TableRow><TableCell>Vencido em aberto</TableCell><TableCell>{current?moneyBR(current.payable.overdue):'—'} <small>{current?.payable.overdueCount||0} títulos</small></TableCell><TableCell>{current?moneyBR(current.receivable.overdue):'—'} <small>{current?.receivable.overdueCount||0} títulos</small></TableCell></TableRow></TableBody></Table>
     <h2>Variação em relação ao período anterior</h2><Table><TableHeader><TableRow><TableHead>Indicador</TableHead><TableHead>Período atual</TableHead><TableHead>Período anterior ({data?.previousFrom?`${fmt(data.previousFrom)} a ${fmt(data.previousTo)}`:'sem dados'})</TableHead><TableHead>Variação</TableHead></TableRow></TableHeader><TableBody>{[['Pagamentos previstos','payable','expected'],['Pagamentos realizados','payable','realized'],['Recebimentos previstos','receivable','expected'],['Recebimentos realizados','receivable','realized']].map(([label,k,metric]:any)=><TableRow key={label}><TableCell>{label}</TableCell><TableCell>{current?.importedRows?moneyBR(current[k][metric]):'— sem dados'}</TableCell><TableCell>{data?.comparison?moneyBR(data.comparison[k][metric]):'Sem base importada'}</TableCell><TableCell>{changeText(current?.importedRows?current[k][metric]:0,data?.comparison?.[k]?.[metric])}</TableCell></TableRow>)}</TableBody></Table>
     <h2>Acompanhamento da tesouraria</h2><div className="metrics"><Metric label="Etapas concluídas" value={String(routines.length)} detail="Registros concluídos no período"/><Metric label="Conferências de cofre" value={String(cashChecks.length)} detail="Lançamentos de conferência"/><Metric label="Pendências em aberto" value={String(openIssues)} detail="Aguardando providência" tone={openIssues?'red':''}/></div>
     <h2>Evolução semanal</h2><Trend rows={current?.weekly||[]} type="week"/><h2>Evolução mensal</h2><Trend rows={current?.monthly||[]} type="month"/>
     {!current?.importedRows&&<p className="erp-empty">Não há títulos importados para este recorte. Importe os arquivos do período antes de salvar um fechamento.</p>}<h2>Variações, impacto e providência</h2>{canWrite&&<textarea className="erp-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre variações relevantes, impacto, justificativa, responsável e prazo da providência."/>}<div className="no-print erp-actions">{canWrite&&<button className="primary" disabled={busy||!current?.importedRows} onClick={closePeriod}><Save size={16}/>{busy?'Salvando…':'Salvar fechamento deste período'}</button>}{saved&&<span><CheckCircle2 size={15}/>Fechamento salvo no histórico.</span>}</div>
    </article>}
   </section>
   <section className="panel"><div className="panel-heading"><div><h2>Fechamentos preservados</h2><p>Consulta de períodos anteriores, com data, responsável e importações de origem.</p></div></div>{!data?.closings?.length?<p>Nenhum fechamento salvo ainda.</p>:<Table><TableHeader><TableRow><TableHead>Período</TableHead><TableHead>Loja</TableHead><TableHead>Gerado em</TableHead><TableHead>Título</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.closings.map((c:any)=><TableRow key={c.id}><TableCell>{fmt(c.period_start)} a {fmt(c.period_end)}</TableCell><TableCell>{c.store}</TableCell><TableCell>{new Date(c.created_at).toLocaleString('pt-BR')}</TableCell><TableCell>{c.title}<small>Por {c.created_by} · {c.source_imports.length} importações vinculadas</small></TableCell><TableCell><button className="text-button" onClick={()=>setSelectedClose(c)}>Abrir resumo</button></TableCell></TableRow>)}</TableBody></Table>}</section>
   {selectedClose&&<section className="panel"><div className="panel-heading"><div><h2>{selectedClose.title}</h2><p>{selectedClose.store} · {fmt(selectedClose.period_start)} a {fmt(selectedClose.period_end)} · salvo em {new Date(selectedClose.created_at).toLocaleString('pt-BR')}</p></div><button className="secondary" onClick={()=>setSelectedClose(null)}>Fechar</button></div><div className="metrics"><Metric label="Pagamentos previstos" value={moneyBR(selectedClose.payload.payable.expected)} detail={`${selectedClose.payload.payable.expectedCount} títulos`}/><Metric label="Pagamentos realizados" value={moneyBR(selectedClose.payload.payable.realized)} detail={`${selectedClose.payload.payable.realizedCount} baixas`}/><Metric label="Recebimentos previstos" value={moneyBR(selectedClose.payload.receivable.expected)} detail={`${selectedClose.payload.receivable.expectedCount} títulos`}/><Metric label="Recebimentos realizados" value={moneyBR(selectedClose.payload.receivable.realized)} detail={`${selectedClose.payload.receivable.realizedCount} baixas`}/></div><p className="preline">{selectedClose.note||'Sem observações.'}</p><small>Importações vinculadas: {selectedClose.source_imports.length}</small></section>}
  </>:<>
   <section className="metrics">{current&&financeKinds.map(k=><><Metric key={k+'-expected'} label={`${k==='payable'?'Previsto a pagar':'Previsto a receber'}`} value={moneyBR(current[k].expected)} detail={`${current[k].expectedCount} títulos por vencimento`} tone={k==='payable'?'red':'green'}/><Metric key={k+'-real'} label={`${k==='payable'?'Pago':'Recebido'} no período`} value={moneyBR(current[k].realized)} detail={`${current[k].realizedCount} títulos com baixa`} /></>)}{current&&financeKinds.map(k=><><Metric key={k+'-overdue'} label="Vencido em aberto" value={moneyBR(current[k].overdue)} detail={`${current[k].overdueCount} títulos vencidos`} tone="red"/><Metric key={k+'-open'} label="Saldo em aberto" value={moneyBR(current[k].open)} detail={`${current[k].openCount} títulos em aberto`}/></>)}</section>
   <section className="panel"><div className="panel-heading"><div><h2>{labels[view]} · resumo do ERP</h2><p>Consolidado por vencimento e baixa; títulos não são recadastrados aqui.</p></div><span className="tag">{loading?'Atualizando…':`${data?.inRangeBatches?.length||0} importações ativas`}</span></div>
    {canWrite&&<div className="erp-import-head"><div><FileSpreadsheet size={20}/><div><strong>Importar arquivo exportado pelo ERP</strong><small>Exporte como CSV UTF-8 e inclua todos os títulos em aberto para refletir o saldo atual. O mapeamento de colunas é salvo para esta leitura.</small></div></div><label className="primary erp-file-button"><Upload size={16}/>Escolher CSV<input type="file" accept=".csv,.txt,.tsv,text/csv,text/plain" onChange={e=>pickFile(e.target.files?.[0]||null)}/></label></div>}
    {canWrite&&table&&<div className="erp-mapper"><div className="erp-map-grid"><label>Tipo de relatório<select value={kind} onChange={e=>setKind(e.target.value)}><option value="payable">Contas a pagar</option><option value="receivable">Contas a receber</option></select></label><label>Loja deste arquivo<select value={importStore} onChange={e=>setImportStore(e.target.value)}>{(data?.stores||stores.filter(s=>s!=='Rede')).filter((s:string)=>s!=='Rede').map((s:string)=><option key={s}>{s}</option>)}</select></label><label>Período inicial<input type="date" value={importFrom} onChange={e=>setImportFrom(e.target.value)}/></label><label>Período final<input type="date" value={importTo} onChange={e=>setImportTo(e.target.value)}/></label></div><p className="erp-file-name">{file?.name} · {table.rows.length.toLocaleString('pt-BR')} linhas encontradas</p><div className="erp-map-grid">{erpFields.map(f=><label key={f.key}>{f.label}{f.required&&<b> *</b>}<select value={mapping[f.key]||''} onChange={e=>setMapping({...mapping,[f.key]:e.target.value})}><option value="">Não usar / selecionar…</option>{table.headers.map((h:string)=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><p className={parsed.errors.length?'erp-error':'erp-ok'}>{parsed.errors.length?`${parsed.errors.length} linha(s) precisam de correção; nenhuma será importada.`:`${parsed.rows.length.toLocaleString('pt-BR')} títulos válidos · total ${moneyBR(parsed.rows.reduce((s:number,r:any)=>s+r.amount,0))}`}</p>{parsed.errors.slice(0,5).map((e:any)=><small className="erp-error" key={e.line+'-'+e.reason}>Linha {e.line}: {e.reason}</small>)}<div className="erp-actions"><button className="secondary" onClick={()=>{setTable(null);setFile(null);}}>Cancelar</button><button className="primary" disabled={busy||parsed.errors.length>0||!parsed.rows.length||!mapping.dueDate||!mapping.amount||importFrom>importTo} onClick={importFile}><Upload size={16}/>{busy?'Importando…':'Importar títulos'}</button></div></div>}
   </section>
   <section className="panel"><div className="panel-heading"><div><h2>Evolução semanal</h2><p>Valores por vencimento e pelas baixas registradas pelo ERP.</p></div></div><Trend rows={current?.weekly.filter((x:any)=>x.kind===view)||[]} type="week"/><h2>Evolução mensal</h2><Trend rows={current?.monthly.filter((x:any)=>x.kind===view)||[]} type="month"/></section>
   <section className="panel"><div className="panel-heading"><div><h2>Detalhamento opcional</h2><p>Consulte títulos importados para investigar um valor ou uma situação específica.</p></div><button className="secondary" onClick={()=>{setDetailKind(detailKind?'':view);setPage(1);}}><Eye size={16}/>{detailKind?'Fechar títulos':'Consultar títulos'}</button></div>{detailKind&&<><Table><TableHeader><TableRow><TableHead>Vencimento</TableHead><TableHead>Fornecedor / cliente</TableHead><TableHead>Documento</TableHead><TableHead>Tipo</TableHead><TableHead>Valor</TableHead><TableHead>Baixado</TableHead><TableHead>Em aberto</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{detail?.rows?.map((r:any)=><TableRow key={r.id}><TableCell>{fmt(r.due_date)}</TableCell><TableCell>{r.name||'—'}</TableCell><TableCell>{r.document||r.external_id}</TableCell><TableCell>{r.category}</TableCell><TableCell>{moneyBR(r.amount)}</TableCell><TableCell>{moneyBR(r.settled)}</TableCell><TableCell>{moneyBR(r.remaining)}</TableCell><TableCell>{r.status}</TableCell></TableRow>)}</TableBody></Table><div className="erp-pager"><span>{detail?`${detail.total} título(s) · página ${page} de ${Math.max(1,Math.ceil(detail.total/50))}`:'Carregando…'}</span><button className="secondary" disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/>Anterior</button><button className="secondary" disabled={!detail||page*50>=detail.total} onClick={()=>setPage(page+1)}>Próxima<ChevronRight size={16}/></button></div></>}</section>
  </>}
  <section className="panel"><div className="panel-heading"><div><h2><History size={18}/> Histórico de importações</h2><p>Arquivo, loja, período, usuário e totais. Reimportar período sobreposto arquiva a versão anterior sem apagá-la.</p></div></div>{!data?.batches?.length?<p>Nenhuma importação registrada. O sistema mantém os dados manuais de tesouraria separados.</p>:<Table><TableHeader><TableRow><TableHead>Data da importação</TableHead><TableHead>Arquivo</TableHead><TableHead>Loja / tipo</TableHead><TableHead>Período do arquivo</TableHead><TableHead>Linhas</TableHead><TableHead>Valor original</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{data.batches.slice(0,30).map((b:any)=><TableRow key={b.id}><TableCell>{new Date(b.imported_at).toLocaleString('pt-BR')}<small>{b.imported_by}</small></TableCell><TableCell>{b.source_filename}</TableCell><TableCell>{b.store} · {labels[b.kind]}</TableCell><TableCell>{fmt(b.period_start)} a {fmt(b.period_end)}</TableCell><TableCell>{b.row_count}</TableCell><TableCell>{moneyBR(b.amount_total)}</TableCell><TableCell><span className={'tag '+(b.active?'success':'')}>{b.active?'Ativa':b.state==='Falhou'?'Falhou':'Arquivada'}</span></TableCell></TableRow>)}</TableBody></Table>}</section>
 </div>;
}
function Trend({rows,type}:{rows:any[];type:'week'|'month'}){if(!rows.length)return <p className="erp-empty">Sem importações suficientes para mostrar a evolução deste período.</p>;return <div className="erp-trend-wrap"><Table><TableHeader><TableRow><TableHead>{periodName(type)}</TableHead><TableHead>Movimento</TableHead><TableHead>Tipo de transação</TableHead><TableHead>Previsto</TableHead><TableHead>Realizado</TableHead><TableHead>Qtde. títulos</TableHead></TableRow></TableHeader><TableBody>{rows.map((r:any)=><TableRow key={r.period+'|'+r.kind+'|'+r.category}><TableCell>{type==='week'?fmt(r.period):r.period}</TableCell><TableCell>{labels[r.kind]}</TableCell><TableCell>{r.category}</TableCell><TableCell>{moneyBR(r.expected)} <small>{r.dueCount} títulos</small></TableCell><TableCell>{moneyBR(r.realized)} <small>{r.paidCount} baixas</small></TableCell><TableCell>{r.dueCount+r.paidCount}</TableCell></TableRow>)}</TableBody></Table></div>;}
