import {categories,stages,today} from './model';
export type Field={key:string;label:string;type?:string;options?:string[];required?:boolean;help?:string};
const f=(key:string,label:string,type='text',options?:string[],required=true):Field=>({key,label,type,options,required});
export const forms:Record<string,{title:string;dateLabel:string;fields:Field[]}>={
 payable:{title:'Conta a pagar',dateLabel:'Vencimento',fields:[f('name','Fornecedor'),f('document','Documento / referência'),f('category','Categoria','select',categories),f('amount','Valor original (R$)','money'),f('status','Situação','select',['Em aberto','Aguardando autorização','Bloqueado','Cancelado']),f('note','Justificativa / observações','textarea',undefined,false)]},
 receivable:{title:'Conta a receber',dateLabel:'Vencimento',fields:[f('name','Cliente / origem'),f('document','Documento / referência'),f('category','Modalidade','select',categories),f('amount','Valor original (R$)','money'),f('status','Situação','select',['Em aberto','Em cobrança','Em acordo','Cancelado']),f('note','Cobrança / acordo / próxima ação','textarea',undefined,false)]},
 routine:{title:'Etapa da rotina',dateLabel:'Data de execução',fields:[f('responsible','Responsável pela execução'),f('movementDate','Data do movimento','date'),f('stage','Etapa','select',stages),f('status','Situação do trabalho','select',['Concluído','Em andamento','Folga','Feriado','Ausência']),f('start','Início','time',undefined,false),f('end','Fim','time',undefined,false),f('volume','Quantidade de itens conferidos','number'),f('note','Justificativa / pendência','textarea',undefined,false)]},
 cash:{title:'Conferência do cofre',dateLabel:'Data da conferência',fields:[f('responsible','Responsável'),f('expected','Saldo esperado (R$)','money'),f('counted','Saldo contado (R$)','money'),f('explained','Diferença explicada (R$ com sinal)','signedmoney'),f('regularization','Regularização','select',['Pendente','Regularizado']),f('note','Itens explicativos / providência','textarea',undefined,false)]},
 difference:{title:'Diferença de caixa',dateLabel:'Data do movimento',fields:[f('operator','Operador(es) / não identificado'),f('cashier','Caixa / sessão'),f('type','Tipo','select',['Sobra','Falta']),f('amount','Valor (R$)','money'),f('cause','Causa identificada','textarea',undefined,false),f('action','Providência / próxima ação'),f('status','Tratamento','select',['Pendente','Em tratamento','Resolvido']),f('note','Observações','textarea',undefined,false)]},
 issue:{title:'Pendência',dateLabel:'Prazo de resolução',fields:[f('name','Assunto'),f('responsible','Responsável pela resolução'),f('priority','Prioridade','select',['Média','Alta','Baixa']),f('status','Situação','select',['Aberto','Em andamento','Aguardando terceiros','Resolvido']),f('impact','Impacto operacional ou financeiro','textarea',undefined,false),f('nextAction','Próxima ação'),f('note','Histórico / retorno recebido','textarea',undefined,false)]},
 account:{title:'Conta e conciliação',dateLabel:'Data da atualização',fields:[f('name','Banco / nome da conta'),f('agency','Agência','text',undefined,false),f('number','Número / identificação'),f('balance','Saldo disponível (R$)','signedmoney'),f('balanceDate','Data do saldo','date'),f('conciledUntil','Conciliada até','date'),f('frequency','Frequência de conciliação','select',['Diária','Semanal','Mensal']),f('status','Situação','select',['Pendente','Conciliada','Não iniciada']),f('note','Bloqueios / justificativas','textarea',undefined,false)]},
 movement:{title:'Movimentação de caixa',dateLabel:'Data do movimento',fields:[f('name','Descrição'),f('account','Conta de origem','account'),f('destination','Conta de destino (transferência)','account',undefined,false),f('type','Tipo','select',['Entrada','Saída','Transferência interna']),f('amount','Valor (R$)','money'),f('note','Observações','textarea',undefined,false)]},
 report:{title:'Enviar relatório',dateLabel:'Data do envio',fields:[f('name','Título'),f('from','Período inicial','date'),f('to','Período final','date'),f('note','Síntese gerencial / decisões necessárias','textarea',undefined,false)]}
};
export function defaults(kind:string){const d:any={};for(const f of forms[kind].fields){d[f.key]=f.type==='date'?today():f.type==='select'?f.options![0]:['money','signedmoney','number'].includes(f.type||'')?0:'';}if(kind==='routine')d.pauses=[];if(kind==='report')d.status='Enviado';return d;}
